networks:
  proxy:
    external: true
    name: ${DOCKER_PROXY_NETWORK}

services:
  nginx:
    build: nginx
    restart: unless-stopped
    networks:
      - proxy
    environment:
      ROOT_DOMAIN_NAME: ${ROOT_DOMAIN_NAME}
      MATRIX_DOMAIN: ${MATRIX_DOMAIN}
      MATRIX_FED_PORT: ${MATRIX_FED_PORT}
