networks:
  proxy:
    external: true
    name: ${DOCKER_PROXY_NETWORK}

services:
  nginx:
    build: nginx
    restart: unless-stopped
    ports:
      - ${NGINX_HTTP_PORT}:80
    environment:
      ROOT_DOMAIN_NAME: ${ROOT_DOMAIN_NAME}
      MATRIX_URL: ${MATRIX_URL}
